#!/usr/bin/env python3
"""
batch_generateur.py
Run generateur.py N times and write the names of every .dot file produced
during each run to an Excel spreadsheet (one run per row, with optional node/edge info).

Usage
-----
python batch_generateur.py 5                       # writes generated_files.xlsx
python batch_generateur.py 10 --xlsx my_runs.xlsx  # custom Excel filename
"""

import argparse
import subprocess
import re
from pathlib import Path
from datetime import datetime

import pandas as pd

# ---------- helpers ----------------------------------------------------------
# Regex that captures .dot paths and optionally num_nodes and num_edges
DOT_STATS_REGEX = re.compile(
    r"""['"]?(?P<path>\.\.[^'"\s]+?\.dot)(?:[^\n]*?num_nodes:(?P<nodes>\d+), num_edges:(?P<edges>\d+))?"""
)


def run_generateur_once() -> list[dict]:
    """
    Execute `python generateur.py` once, capture stdout,
    and return a list of dicts with .dot file path, num_nodes, and num_edges.
    """
    result = subprocess.run(
        ["python", "generateur.py"],
        text=True,
        capture_output=True,
        check=True,
    )

    entries = []
    for m in DOT_STATS_REGEX.finditer(result.stdout):
        entries.append({
            "filename": m.group("path"),
            "num_nodes": int(m.group("nodes")) if m.group("nodes") else None,
            "num_edges": int(m.group("edges")) if m.group("edges") else None,
        })
    return entries


def pad_rows(rows: list[list[dict]]) -> pd.DataFrame:
    """
    Convert a ragged list of dict rows into a flat DataFrame with columns:
    file1_name, file1_nodes, file1_edges, file2_name, ...
    """
    max_len = max(len(r) for r in rows)
    padded = [row + [{}] * (max_len - len(row)) for row in rows]

    flat_data = []
    for row in padded:
        flat_row = {}
        for i, entry in enumerate(row):
            flat_row[f"file{i+1}_name"] = entry.get("filename")
            flat_row[f"file{i+1}_nodes"] = entry.get("num_nodes")
            flat_row[f"file{i+1}_edges"] = entry.get("num_edges")
        flat_data.append(flat_row)

    return pd.DataFrame(flat_data)


# ---------- main -------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Batch‑run generateur.py")
    parser.add_argument("n", type=int, help="number of times to run generateur.py")
    parser.add_argument(
        "--xlsx",
        default=f"generated_files_{datetime.now():%Y%m%d_%H%M%S}.xlsx",
        help="Excel output filename (default: autogenerated timestamped name)",
    )
    args = parser.parse_args()

    all_rows: list[list[dict]] = []

    for i in range(args.n):
        print(f"Run {i+1}/{args.n}…", end="", flush=True)
        try:
            files_this_run = run_generateur_once()
            all_rows.append(files_this_run)
            print(f" captured {len(files_this_run)} file(s).")
        except subprocess.CalledProcessError as exc:
            print("\nError running generateur.py:\n", exc.stderr)
            raise SystemExit(1)

    df = pad_rows(all_rows)

    # Ensure the parent directory for the xlsx exists
    excel_path = Path(args.xlsx).expanduser().resolve()
    excel_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_excel(excel_path, index=False)
    print(f"\n✓ Saved results to {excel_path}")


if __name__ == "__main__":
    main()
